#TODO: homepage that list projects for each user  

go_to_backlog:
  pattern: /Backlog/{owner}/{project}/
  defaults: { _controller: ProjectBundle:Default:list }   

go_to_User_Story:
  pattern: /Backlog/{owner}/{project}/Add_UserStory/
  defaults: { _controller: ProjectBundle:Default:Add_Us }   

Delete_User_Story:
  pattern: /Backlog/{owner}/{project}/delete_UserStory/{id}
  defaults: { _controller: ProjectBundle:Default:Delete_Us }   

Update_User_Story:
  pattern: /Backlog/{owner}/{project}/update_UserStory/{id}
  defaults: { _controller: ProjectBundle:Default:Update_Us }   
  
Project:
    pattern: /Project/{owner}/{project}
    defaults: { _controller: ProjectBundle:Default:ProjectOverview }
    

    
Sprint_creation:
    pattern: /Sprint/new/{owner}/{project}
    defaults: { _controller: ProjectBundle:Sprint:SprintCreation }
    
Sprint_task_list:
    pattern: /Sprint/list/{owner}/{project}/{sprintId}/{kanban_view}
    defaults: { _controller: ProjectBundle:Sprint:SprintList }
Sprint_task_delete:
    pattern: /Sprint/delete/{owner}/{project}/{sprintId}/{taskId}
    defaults: { _controller: ProjectBundle:Sprint:SprintListDeleteTask }



go_to_Kanban:
  pattern: /Kanban/{owner}/{project}/{sprint}/visualisation/
  defaults: { _controller: ProjectBundle:Kanban:visualisation } 

oG_Update_Achievement:
  pattern: /Kanban/{owner}/{project}/{sprint}/Update_task_achievement_OG/{id}
  defaults: { _controller: ProjectBundle:Kanban:Update_task_achievementoG }

Done_Update_Achievement:
  pattern: /Kanban/{owner}/{project}/{sprint}/Update_task_achievement_Done/{id}
  defaults: { _controller: ProjectBundle:Kanban:Update_task_achievementD }

ToDo_Update_Achievement:
  pattern: /Kanban/{owner}/{project}/{sprint}/Update_task_achievement_ToDo/{id}
  defaults: { _controller: ProjectBundle:Kanban:Update_task_achievementToDo }



go_to_task:
  pattern: /Task/Add_Task/{owner}/{project}/{sprint}
  defaults: { _controller: ProjectBundle:Default:Add_Task }  

Update_Task:
  pattern: /Task/update_Task/{owner}/{project}/{sprint}/{id}
  defaults: { _controller: ProjectBundle:Default:Update_Task } 

Delete_Task:
  pattern: /Task/deleteTask/{owner}/{project}/{sprint}/{id}
  defaults: { _controller: ProjectBundle:Default:Delete_Task } 


edit_real_gantt:
    pattern: /Gantt/Edit/{owner}/{project}/{sprint}
    defaults: { _controller: ProjectBundle:Gantt:editGAntt }
    
    
add_repo:
    pattern: /Repo/add/{owner}/{project}
    defaults: { _controller: ProjectBundle:Repo:AddRepo }
get_commits:
    pattern: /Repo/getCommits/{owner}/{repo}
    defaults: { _controller: ProjectBundle:Repo:GetCommits }
